/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface ICommodity {
    country?: string;
    name?: string;
    variableOverhead?: number;
}
export interface ICommodityArgs {
    country?: string;
    name?: string;
    variableOverhead?: number;
}
export const CommodityCodec: thrift.IStructCodec<ICommodityArgs, ICommodity> = {
    encode(args: ICommodityArgs, output: thrift.TProtocol): void {
        const obj: any = {
            country: args.country,
            name: args.name,
            variableOverhead: args.variableOverhead
        };
        output.writeStructBegin("Commodity");
        if (obj.country != null) {
            output.writeFieldBegin("country", thrift.TType.STRING, 1);
            output.writeString(obj.country);
            output.writeFieldEnd();
        }
        if (obj.name != null) {
            output.writeFieldBegin("name", thrift.TType.STRING, 2);
            output.writeString(obj.name);
            output.writeFieldEnd();
        }
        if (obj.variableOverhead != null) {
            output.writeFieldBegin("variableOverhead", thrift.TType.DOUBLE, 3);
            output.writeDouble(obj.variableOverhead);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): ICommodity {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.country = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.name = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.DOUBLE) {
                        const value_3: number = input.readDouble();
                        _args.variableOverhead = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            country: _args.country,
            name: _args.name,
            variableOverhead: _args.variableOverhead
        };
    }
};
export class Commodity extends thrift.StructLike implements ICommodity {
    public country?: string;
    public name?: string;
    public variableOverhead?: number;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: ICommodityArgs = {}) {
        super();
        if (args.country != null) {
            const value_4: string = args.country;
            this.country = value_4;
        }
        if (args.name != null) {
            const value_5: string = args.name;
            this.name = value_5;
        }
        if (args.variableOverhead != null) {
            const value_6: number = args.variableOverhead;
            this.variableOverhead = value_6;
        }
    }
    public static read(input: thrift.TProtocol): Commodity {
        return new Commodity(CommodityCodec.decode(input));
    }
    public static write(args: ICommodityArgs, output: thrift.TProtocol): void {
        return CommodityCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return CommodityCodec.encode(this, output);
    }
}
